### ISSUE TITLE
( 安装说明？) Installation Instructions?

### ISSUE THREAD

**Issue by Oshekher** [inis-cloud/theme#1]
Atleast tell properly where to get api and all or make video installation on webhosting. @inis-cloud @racns 

至少正确地告诉从哪里获取 api 和所有或制作安装视频  @inis-cloud @racns

**Comment by racns** [comment]
> Atleast tell properly where to get api and all or make video installation on webhosting. @inis-cloud @racns
> 
> 至少正确地告诉从哪里获取 api 和所有或制作安装视频 @inis-cloud @racns

在描述文件中的是“使用说明”绿字就是API文档和安装说明，或者你可以打开网址：https://docs.inis.cc
